name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/deadvertex/vk_cinematic_buildenv:latest
    - name: Publish the Docker image
      run: docker push ghcr.io/deadvertex/vk_cinematic_buildenv:latest
